### ISSUE TITLE
issue when add more than 3 images

### ISSUE THREAD

**Issue by macroramesh6** [dreyacosta/pure-responsive-css3-slider#1]
three images only displaying in slide. can you help me. i have six slides in my sideshow?

**Comment by dreyacosta** [comment]
You have just to do some maths and add rules to your keyframes.

If you're using a preprocessor like Stylus you can do a function to avoid repetitions. 

Something like this:

``` css
@keyframes slide-animation {
  1% {left: 0%; opacity: 1;}
  14.3% {left: 0%; opacity: 1}
  15.3% {opacity: 0.2;}
  16.3% {left: -100%; opacity: 1;}
  30.6% {left: -100%; opacity: 1}
  31.6% {opacity: 0.2;}
  32.6% {left: -200%; opacity: 1;}
  46.9% {left: -200%; opacity: 1}
  47.9% {opacity: 0.2;}
  48.9% {left: -300%; opacity: 1;}
  63.2% {left: -300%; opacity: 1}
  64.2% {opacity: 0.2;}
  65.2% {left: -400%; opacity: 1;}
  79.5% {left: -400%; opacity: 1}
  80.5% {opacity: 0.2;}
  81.5% {left: -500%; opacity: 1;}
  95.5% {left: -500%; opacity: 1}
  96.5% {opacity: 0.2;}
  100% {left: 0%;}
}
```
